// Generated by GitHub Copilot

/**
 * Represents a single multiple-choice question.
 */
export interface Question {
  id: number;
  text: string;
  options: string[];
}

/**
 * Holds parsed quiz data: questions and corresponding answer key.
 */
export interface QuizData {
  questions: Question[];
  answerKey: string[];
}

/**
 * A paper saved to localStorage with a title and timestamp.
 */
export interface SavedPaper {
  id: string;
  title: string;
  questions: Question[];
  answerKey: string[];
  createdAt: string;
}

/**
 * Stores the result of a completed exam.
 */
export interface ExamResult {
  total: number;
  attempted: number;
  correct: number;
  wrong: number;
  score: number;
}

/**
 * A single question review item showing the question, options,
 * user's selected answer, and the correct answer.
 */
export interface ReviewItem {
  questionNumber: number;
  text: string;
  options: string[];
  selectedAnswer: string;
  correctAnswer: string;
  isCorrect: boolean;
}
