// Generated by GitHub Copilot
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { DatePipe } from '@angular/common';
import { QuizService } from '../../services/quiz.service';
import { SavedPaper } from '../../models/quiz.model';

/**
 * Lists imported paper JSON files.
 * Previously imported papers are cached in localStorage and shown automatically.
 * Users can import new .json files, start a paper, or remove it from the list.
 */
@Component({
  selector: 'app-papers',
  standalone: true,
  imports: [DatePipe],
  templateUrl: './papers.component.html',
  styleUrl: './papers.component.css',
})
export class PapersComponent implements OnInit {
  papers: SavedPaper[] = [];
  errorMessage = '';

  constructor(
    private quizService: QuizService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.papers = this.quizService.getCachedPapers();
  }

  /**
   * Handles file input change — reads selected JSON files, adds to list and cache.
   */
  async onFilesSelected(event: Event): Promise<void> {
    const input = event.target as HTMLInputElement;
    if (!input.files || input.files.length === 0) {
      return;
    }
    this.errorMessage = '';

    try {
      const imported = await this.quizService.readPaperFiles(input.files);
      for (const paper of imported) {
        if (!this.papers.some((p) => p.id === paper.id)) {
          this.papers.push(paper);
        }
      }
      this.quizService.cachePapers(this.papers);
    } catch (err) {
      this.errorMessage = err instanceof Error ? err.message : 'Failed to import files.';
    }

    input.value = '';
  }

  /**
   * Loads the selected paper into quiz state and navigates to the summary page.
   */
  startPaper(paper: SavedPaper): void {
    this.quizService.setQuizData({ questions: paper.questions, answerKey: paper.answerKey });
    this.router.navigate(['/summary']);
  }

  /**
   * Removes a paper from the list and from the localStorage cache.
   */
  removePaper(id: string): void {
    this.papers = this.papers.filter((p) => p.id !== id);
    this.quizService.cachePapers(this.papers);
  }

  /**
   * Navigates to the input page to create a new paper.
   */
  createNew(): void {
    this.router.navigate(['/']);
  }
}
