// Generated by GitHub Copilot
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { QuizService } from '../../services/quiz.service';
import { ReviewItem } from '../../models/quiz.model';

/**
 * Review page showing every question with the user's selected answer
 * and the correct answer, colour-coded for quick scanning.
 */
@Component({
  selector: 'app-review',
  standalone: true,
  templateUrl: './review.component.html',
  styleUrl: './review.component.css',
})
export class ReviewComponent implements OnInit {
  reviewItems: ReviewItem[] = [];

  constructor(
    private quizService: QuizService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.reviewItems = this.quizService.getReviewData();
  }

  /**
   * Maps option index (0-3) to letter (A-D).
   */
  optionLetter(index: number): string {
    return String.fromCharCode(65 + index);
  }

  /**
   * Navigates back to the result page.
   */
  backToResults(): void {
    this.router.navigate(['/result']);
  }
}
