// Generated by GitHub Copilot
import { Component, Input, Output, EventEmitter } from '@angular/core';

/**
 * A grid palette showing question numbers with visual state for
 * answered, current, and unanswered questions.
 * Accessibility: each button is labeled and keyboard-navigable.
 */
@Component({
  selector: 'app-question-palette',
  standalone: true,
  templateUrl: './question-palette.component.html',
  styleUrl: './question-palette.component.css',
})
export class QuestionPaletteComponent {
  @Input() totalQuestions = 0;
  @Input() currentIndex = 0;
  @Input() answeredSet = new Set<number>();
  @Output() navigate = new EventEmitter<number>();

  /**
   * Emits the selected question index to the parent component.
   */
  goTo(index: number): void {
    this.navigate.emit(index);
  }

  getState(index: number): string {
    if (index === this.currentIndex) {
      return 'current';
    }
    if (this.answeredSet.has(index + 1)) {
      return 'answered';
    }
    return 'unanswered';
  }
}
