// Generated by GitHub Copilot
import { Routes } from '@angular/router';
import { quizDataGuard } from './guards/quiz.guard';

/**
 * Application routes.
 * - '' (home): Input page to create a new paper
 * - 'papers': Lists all saved papers
 * - Summary, exam, and result are guarded to require loaded quiz data.
 */
export const routes: Routes = [
  {
    path: '',
    loadComponent: () =>
      import('./pages/input/input.component').then((m) => m.InputComponent),
  },
  {
    path: 'papers',
    loadComponent: () =>
      import('./pages/papers/papers.component').then((m) => m.PapersComponent),
  },
  {
    path: 'summary',
    loadComponent: () =>
      import('./pages/summary/summary.component').then((m) => m.SummaryComponent),
    canActivate: [quizDataGuard],
  },
  {
    path: 'exam',
    loadComponent: () =>
      import('./pages/exam/exam.component').then((m) => m.ExamComponent),
    canActivate: [quizDataGuard],
  },
  {
    path: 'result',
    loadComponent: () =>
      import('./pages/result/result.component').then((m) => m.ResultComponent),
    canActivate: [quizDataGuard],
  },
  {
    path: 'review',
    loadComponent: () =>
      import('./pages/review/review.component').then((m) => m.ReviewComponent),
    canActivate: [quizDataGuard],
  },
  {
    path: '**',
    redirectTo: '',
  },
];
