// Generated by GitHub Copilot
import { Injectable } from '@angular/core';
import { BehaviorSubject, interval, map, takeWhile, Subject } from 'rxjs';
import { Question, QuizData, ExamResult, SavedPaper, ReviewItem } from '../models/quiz.model';

/**
 * Shared service managing quiz state: questions, answers, timer, results,
 * and localStorage persistence for saved papers.
 */
@Injectable({ providedIn: 'root' })
export class QuizService {
  private readonly EXAM_DURATION_SECONDS = 90 * 60;
  private readonly STORAGE_KEY = 'quiz_saved_papers';

  private questions: Question[] = [];
  private answerKey: string[] = [];
  private userAnswers = new Map<number, string>();
  private remainingSeconds = this.EXAM_DURATION_SECONDS;
  private timerRunning = false;
  private stopTimer$ = new Subject<void>();

  readonly remainingSeconds$ = new BehaviorSubject<number>(this.EXAM_DURATION_SECONDS);
  readonly timerExpired$ = new Subject<void>();

  /**
   * Returns true when quiz data has been loaded.
   */
  hasData(): boolean {
    return this.questions.length > 0;
  }

  /**
   * Stores parsed questions and answer key. Resets any previous exam state.
   */
  setQuizData(data: QuizData): void {
    this.questions = data.questions;
    this.answerKey = data.answerKey;
    this.userAnswers.clear();
    this.remainingSeconds = this.EXAM_DURATION_SECONDS;
    this.remainingSeconds$.next(this.EXAM_DURATION_SECONDS);
  }

  // ── File-based persistence ─────────────────────────────────────

  /**
   * Saves a paper as a downloadable JSON file and caches it in localStorage.
   */
  savePaper(title: string, questions: Question[], answerKey: string[]): void {
    const paper: SavedPaper = {
      id: crypto.randomUUID(),
      title,
      questions,
      answerKey,
      createdAt: new Date().toISOString(),
    };

    // Cache to localStorage
    const cached = this.getCachedPapers();
    cached.push(paper);
    this.cachePapers(cached);

    // Download as JSON file
    const json = JSON.stringify(paper, null, 2);
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);

    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `${title.replace(/[^a-zA-Z0-9_-]/g, '_')}.json`;
    anchor.click();

    URL.revokeObjectURL(url);
  }

  /**
   * Reads a single JSON File and returns a SavedPaper.
   * Validates the required fields before returning.
   */
  readPaperFile(file: File): Promise<SavedPaper> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => {
        try {
          const paper = JSON.parse(reader.result as string) as SavedPaper;
          if (!paper.title || !Array.isArray(paper.questions) || !Array.isArray(paper.answerKey)) {
            reject(new Error(`Invalid paper format in "${file.name}".`));
            return;
          }
          if (!paper.id) {
            paper.id = crypto.randomUUID();
          }
          resolve(paper);
        } catch {
          reject(new Error(`Failed to parse "${file.name}".`));
        }
      };
      reader.onerror = () => reject(new Error(`Could not read "${file.name}".`));
      reader.readAsText(file);
    });
  }

  /**
   * Reads multiple JSON files and returns all valid SavedPapers.
   */
  async readPaperFiles(files: FileList): Promise<SavedPaper[]> {
    const papers: SavedPaper[] = [];
    for (let i = 0; i < files.length; i++) {
      const paper = await this.readPaperFile(files[i]);
      papers.push(paper);
    }
    return papers;
  }

  // ── localStorage cache ─────────────────────────────────────────

  /**
   * Returns all cached papers from localStorage.
   */
  getCachedPapers(): SavedPaper[] {
    const raw = localStorage.getItem(this.STORAGE_KEY);
    if (!raw) {
      return [];
    }
    try {
      return JSON.parse(raw) as SavedPaper[];
    } catch {
      return [];
    }
  }

  /**
   * Saves the full list of papers to localStorage.
   */
  cachePapers(papers: SavedPaper[]): void {
    localStorage.setItem(this.STORAGE_KEY, JSON.stringify(papers));
  }

  /**
   * Removes a single paper from the localStorage cache by ID.
   */
  removeCachedPaper(id: string): void {
    const papers = this.getCachedPapers().filter((p) => p.id !== id);
    this.cachePapers(papers);
  }

  getQuestions(): Question[] {
    return this.questions;
  }

  getQuestion(index: number): Question | undefined {
    return this.questions[index];
  }

  getTotalQuestions(): number {
    return this.questions.length;
  }

  getExamDurationMinutes(): number {
    return this.EXAM_DURATION_SECONDS / 60;
  }

  setAnswer(questionId: number, answer: string): void {
    this.userAnswers.set(questionId, answer);
  }

  getAnswer(questionId: number): string | undefined {
    return this.userAnswers.get(questionId);
  }

  getUserAnswers(): Map<number, string> {
    return new Map(this.userAnswers);
  }

  /**
   * Starts the countdown timer. Emits timerExpired$ when time runs out.
   */
  startTimer(): void {
    if (this.timerRunning) {
      return;
    }
    this.timerRunning = true;

    interval(1000)
      .pipe(
        takeWhile(() => this.remainingSeconds > 0 && this.timerRunning),
        map(() => {
          this.remainingSeconds--;
          return this.remainingSeconds;
        })
      )
      .subscribe({
        next: (seconds) => {
          this.remainingSeconds$.next(seconds);
          if (seconds <= 0) {
            this.timerRunning = false;
            this.timerExpired$.next();
          }
        },
      });
  }

  stopTimer(): void {
    this.timerRunning = false;
    this.stopTimer$.next();
  }

  /**
   * Evaluates user answers against the answer key and returns the result.
   */
  evaluateExam(): ExamResult {
    this.stopTimer();
    const total = this.questions.length;
    let attempted = 0;
    let correct = 0;

    for (let i = 0; i < total; i++) {
      const questionId = this.questions[i].id;
      const userAnswer = this.userAnswers.get(questionId);
      if (userAnswer) {
        attempted++;
        if (userAnswer.toUpperCase() === this.answerKey[i].toUpperCase()) {
          correct++;
        }
      }
    }

    const wrong = attempted - correct;
    const score = total > 0 ? Math.round((correct / total) * 100) : 0;

    return { total, attempted, correct, wrong, score };
  }

  /**
   * Returns review data for all questions: user's answer vs correct answer.
   */
  getReviewData(): ReviewItem[] {
    return this.questions.map((q, i) => {
      const selected = this.userAnswers.get(q.id) ?? '';
      const correct = this.answerKey[i];
      return {
        questionNumber: i + 1,
        text: q.text,
        options: q.options,
        selectedAnswer: selected,
        correctAnswer: correct,
        isCorrect: selected.toUpperCase() === correct.toUpperCase(),
      };
    });
  }

  /**
   * Fully resets quiz state for a fresh start.
   */
  reset(): void {
    this.questions = [];
    this.answerKey = [];
    this.userAnswers.clear();
    this.stopTimer();
    this.remainingSeconds = this.EXAM_DURATION_SECONDS;
    this.remainingSeconds$.next(this.EXAM_DURATION_SECONDS);
  }

  /**
   * Parses structured text input into Question[].
   *
   * Expected format:
   * ```
   * 1. Question text here?
   * A) Option one
   * B) Option two
   * C) Option three
   * D) Option four
   *
   * 2. Next question?
   * A) ...
   * ```
   *
   * Also supports:
   * - `A.` or `a)` or `a.` prefixes
   * - Questions without numbering (detected by lack of option prefix)
   */
  parseQuestions(raw: string): Question[] {
    const questions: Question[] = [];
    const blocks = raw.trim().split(/\n\s*\n/);

    for (const block of blocks) {
      const lines = block
        .split('\n')
        .map((l) => l.trim())
        .filter((l) => l.length > 0);

      if (lines.length < 2) {
        continue;
      }

      const optionRegex = /^[A-Da-d][).]\s*/;
      const questionLines: string[] = [];
      const options: string[] = [];

      for (const line of lines) {
        if (optionRegex.test(line)) {
          options.push(line.replace(optionRegex, '').trim());
        } else {
          questionLines.push(line.replace(/^\d+[).]\s*/, '').trim());
        }
      }

      if (questionLines.length > 0 && options.length >= 2) {
        questions.push({
          id: questions.length + 1,
          text: questionLines.join(' '),
          options,
        });
      }
    }

    return questions;
  }

  /**
   * Parses answer key text into an array of uppercase letters.
   *
   * Supports formats:
   * - One per line: `1. A` or `A` or `1) A`
   * - Comma-separated: `A, B, C, D`
   */
  parseAnswerKey(raw: string): string[] {
    const trimmed = raw.trim();

    if (trimmed.includes(',')) {
      return trimmed.split(',').map((a) => a.trim().toUpperCase());
    }

    return trimmed
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line.length > 0)
      .map((line) => {
        const match = line.match(/[A-Da-d]/);
        return match ? match[0].toUpperCase() : '';
      })
      .filter((a) => a.length > 0);
  }
}
