// Generated by GitHub Copilot
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Router } from '@angular/router';
import { AsyncPipe } from '@angular/common';
import { Subscription } from 'rxjs';
import { QuizService } from '../../services/quiz.service';
import { QuestionPaletteComponent } from '../../components/question-palette/question-palette.component';
import { Question } from '../../models/quiz.model';

/**
 * Exam page displaying one question at a time with a countdown timer,
 * navigation controls, and a question palette sidebar.
 */
@Component({
  selector: 'app-exam',
  standalone: true,
  imports: [AsyncPipe, QuestionPaletteComponent],
  templateUrl: './exam.component.html',
  styleUrl: './exam.component.css',
})
export class ExamComponent implements OnInit, OnDestroy {
  currentIndex = 0;
  currentQuestion: Question | undefined;
  selectedOption = '';
  totalQuestions = 0;
  answeredSet = new Set<number>();

  private timerSub: Subscription | undefined;

  constructor(
    protected quizService: QuizService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.totalQuestions = this.quizService.getTotalQuestions();
    this.loadQuestion(0);

    this.timerSub = this.quizService.timerExpired$.subscribe(() => {
      this.submitExam();
    });
  }

  ngOnDestroy(): void {
    this.timerSub?.unsubscribe();
  }

  loadQuestion(index: number): void {
    this.currentIndex = index;
    this.currentQuestion = this.quizService.getQuestion(index);
    const saved = this.currentQuestion
      ? this.quizService.getAnswer(this.currentQuestion.id)
      : undefined;
    this.selectedOption = saved ?? '';
  }

  selectOption(option: string): void {
    this.selectedOption = option;
    if (this.currentQuestion) {
      this.quizService.setAnswer(this.currentQuestion.id, option);
      this.answeredSet.add(this.currentQuestion.id);
    }
  }

  /**
   * Maps option index (0-3) to letter (A-D).
   */
  optionLetter(index: number): string {
    return String.fromCharCode(65 + index);
  }

  next(): void {
    if (this.currentIndex < this.totalQuestions - 1) {
      this.loadQuestion(this.currentIndex + 1);
    }
  }

  previous(): void {
    if (this.currentIndex > 0) {
      this.loadQuestion(this.currentIndex - 1);
    }
  }

  goToQuestion(index: number): void {
    this.loadQuestion(index);
  }

  submitExam(): void {
    this.router.navigate(['/result']);
  }

  /**
   * Formats remaining seconds as MM:SS for display.
   */
  formatTime(seconds: number): string {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    return `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
  }
}
