// Generated by GitHub Copilot
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { QuizService } from '../../services/quiz.service';

/**
 * Summary page showing quiz metadata and a button to begin the exam.
 */
@Component({
  selector: 'app-summary',
  standalone: true,
  templateUrl: './summary.component.html',
  styleUrl: './summary.component.css',
})
export class SummaryComponent {
  totalQuestions: number;
  examDuration: number;

  constructor(
    private quizService: QuizService,
    private router: Router
  ) {
    this.totalQuestions = this.quizService.getTotalQuestions();
    this.examDuration = this.quizService.getExamDurationMinutes();
  }

  /**
   * Starts the exam timer and navigates to the exam page.
   */
  startPaper(): void {
    this.quizService.startTimer();
    this.router.navigate(['/exam']);
  }
}
