// Generated by GitHub Copilot
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { QuizService } from '../../services/quiz.service';

/**
 * Input page where users enter a paper title, paste questions, and answer key.
 * On submit the paper is downloaded as a JSON file and the user is redirected
 * to the papers list page.
 */
@Component({
  selector: 'app-input',
  standalone: true,
  imports: [ReactiveFormsModule],
  templateUrl: './input.component.html',
  styleUrl: './input.component.css',
})
export class InputComponent {
  form: FormGroup;
  errorMessage = '';

  constructor(
    private fb: FormBuilder,
    private quizService: QuizService,
    private router: Router
  ) {
    this.form = this.fb.group({
      titleInput: ['', Validators.required],
      questionsInput: ['', Validators.required],
      answerKeyInput: ['', Validators.required],
    });
  }

  /**
   * Validates, parses, downloads paper as JSON file, then navigates to papers list.
   */
  onSubmit(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.errorMessage = '';

    const title = (this.form.value.titleInput as string).trim();
    const rawQuestions = this.form.value.questionsInput as string;
    const rawAnswers = this.form.value.answerKeyInput as string;

    const questions = this.quizService.parseQuestions(rawQuestions);
    const answerKey = this.quizService.parseAnswerKey(rawAnswers);

    if (questions.length === 0) {
      this.errorMessage = 'Could not parse any questions. Please check the format.';
      return;
    }

    if (answerKey.length === 0) {
      this.errorMessage = 'Could not parse the answer key. Please check the format.';
      return;
    }

    if (questions.length !== answerKey.length) {
      this.errorMessage = `Mismatch: found ${questions.length} questions but ${answerKey.length} answers.`;
      return;
    }

    this.quizService.savePaper(title, questions, answerKey);
    this.router.navigate(['/papers']);
  }
}
