// Generated by GitHub Copilot
import { inject } from '@angular/core';
import { CanActivateFn, Router } from '@angular/router';
import { QuizService } from '../services/quiz.service';

/**
 * Route guard that prevents navigation to exam/summary/result pages
 * when no quiz data has been loaded. Redirects to the papers list.
 */
export const quizDataGuard: CanActivateFn = () => {
  const quizService = inject(QuizService);
  const router = inject(Router);

  if (quizService.hasData()) {
    return true;
  }

  return router.createUrlTree(['/papers']);
};
